"""add_schedules_table

Revision ID: 2727514d7ad8
Revises: f248211a7932
Create Date: 2026-06-03 23:11:32.816969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2727514d7ad8'
down_revision: Union[str, Sequence[str], None] = 'f248211a7932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('spider_name', sa.String(length=128), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('params', mysql.JSON(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='schedulestatus'), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_owner_user_id'), 'schedules', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_schedules_spider_name'), 'schedules', ['spider_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_spider_name'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_owner_user_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
