"""add_schedules_table_and_user_isolation

Revision ID: f248211a7932
Revises: 547b6c8b0865
Create Date: 2026-06-03 23:09:51.508186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f248211a7932'
down_revision: Union[str, Sequence[str], None] = '547b6c8b0865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spiders', sa.Column('owner_user_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_spiders_owner_user_id'), 'spiders', ['owner_user_id'], unique=False)
    op.add_column('tasks', sa.Column('owner_user_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_tasks_owner_user_id'), 'tasks', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_owner_user_id'), table_name='tasks')
    op.drop_column('tasks', 'owner_user_id')
    op.drop_index(op.f('ix_spiders_owner_user_id'), table_name='spiders')
    op.drop_column('spiders', 'owner_user_id')
    # ### end Alembic commands ###
